#!/usr/bin/env node
/**
 * Interactive onboarding wizard.
 *
 *   pnpm setup
 *
 * Writes .env, patches site.config.ts brand/url, and (opt-in) collects each
 * integration credential. Only the CORE block is required; every integration
 * is prompted y/n and skipped unless you enable it.
 *
 * No external deps — uses node:readline/promises.
 */
import { createInterface } from "node:readline/promises";
import { stdin, stdout } from "node:process";
import { randomBytes } from "node:crypto";
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const rl = createInterface({ input: stdin, output: stdout });

const ask = async (q, def = "") => {
  const a = (await rl.question(def ? `${q} [${def}]: ` : `${q}: `)).trim();
  return a || def;
};
const yes = async (q, def = false) => {
  const a = (await rl.question(`${q} (${def ? "Y/n" : "y/N"}): `)).trim().toLowerCase();
  if (!a) return def;
  return a === "y" || a === "yes";
};

const env = {};
const set = (k, v) => {
  if (v !== undefined && v !== "") env[k] = v;
};

console.log("\n  Website Builder Optimizer — setup\n  =================================\n");

// ── Core ────────────────────────────────────────────────────────────────────
const brand = await ask("Brand name", "Acme");
const siteUrl = (await ask("Site URL (no trailing slash)", "http://localhost:3000")).replace(
  /\/$/,
  "",
);
const useSqlite = await yes("Use bundled SQLite for local dev?", true);
let dbUri;
if (useSqlite) {
  dbUri = "file:./payload.db";
} else {
  dbUri = await ask("Postgres connection string (Neon pooled URL recommended)");
  const direct = await ask("Postgres DIRECT url for migrations (optional)");
  set("DATABASE_URI_DIRECT", direct);
}
set("DATABASE_URI", dbUri);
set("PAYLOAD_SECRET", randomBytes(32).toString("hex"));
set("NEXT_PUBLIC_SITE_URL", siteUrl);
set("NEXT_PUBLIC_VERCEL_ENV", "development");

// ── Optional integrations ───────────────────────────────────────────────────
console.log("\n  Optional integrations — enable only what you need.\n");

if (await yes("Enable blog translation + image generation (OpenRouter)?")) {
  set("OPENROUTER_API_KEY", await ask("  OPENROUTER_API_KEY"));
}
if (await yes("Enable GA4 + Search Console analytics?")) {
  set("GOOGLE_WORKSPACE_CLI_CLIENT_ID", await ask("  Google OAuth client id"));
  set("GOOGLE_WORKSPACE_CLI_CLIENT_SECRET", await ask("  Google OAuth client secret"));
  set("GA4_PROPERTY_ID", await ask("  GA4 property id (optional)"));
  set("GSC_SITE_URL", await ask("  Search Console site URL (optional)", siteUrl));
  console.log("  → After setup, mint the token: node scripts/mint-google-refresh-token.mjs");
}
if (await yes("Enable PageSpeed Insights?")) {
  set("PAGESPEED_API_KEY", await ask("  PAGESPEED_API_KEY"));
}
if (await yes("Enable Google Ads automation?")) {
  set("GOOGLE_ADS_DEVELOPER_TOKEN", await ask("  GOOGLE_ADS_DEVELOPER_TOKEN"));
  set("GOOGLE_ADS_CLIENT_ID", await ask("  GOOGLE_ADS_CLIENT_ID"));
  set("GOOGLE_ADS_CLIENT_SECRET", await ask("  GOOGLE_ADS_CLIENT_SECRET"));
  set("GOOGLE_ADS_LOGIN_CUSTOMER_ID", await ask("  GOOGLE_ADS_LOGIN_CUSTOMER_ID (MCC)"));
  set("GOOGLE_ADS_CUSTOMER_ID", await ask("  GOOGLE_ADS_CUSTOMER_ID"));
  console.log("  → After setup, mint the token: node scripts/mint-google-ads-token.mjs");
}
if (await yes("Configure a lead-form destination?")) {
  const webhook = await ask("  Webhook URL (blank to use Resend)");
  if (webhook) {
    set("FORM_WEBHOOK_URL", webhook);
    set("FORM_WEBHOOK_SECRET", await ask("  Webhook secret (optional)"));
  } else {
    set("RESEND_API_KEY", await ask("  RESEND_API_KEY"));
  }
}

// ── Write .env ──────────────────────────────────────────────────────────────
const envPath = join(ROOT, ".env");
if (existsSync(envPath) && !(await yes("\n.env exists — overwrite?", false))) {
  console.log("Aborted; .env left unchanged.");
  rl.close();
  process.exit(0);
}
const body =
  "# Generated by `pnpm setup`. See .env.example for the full catalog.\n" +
  Object.entries(env)
    .map(([k, v]) => `${k}=${v}`)
    .join("\n") +
  "\n";
writeFileSync(envPath, body);
console.log(`\n✓ Wrote ${envPath}`);

// ── Patch site.config.ts brand + url ────────────────────────────────────────
const cfgPath = join(ROOT, "site.config.ts");
if (existsSync(cfgPath) && brand !== "Acme") {
  let cfg = readFileSync(cfgPath, "utf8");
  cfg = cfg.replaceAll("Acme", brand).replace("https://example.com", siteUrl);
  writeFileSync(cfgPath, cfg);
  console.log(`✓ Patched site.config.ts (brand → "${brand}")`);
}

console.log(
  "\nNext:\n" +
    "  pnpm generate:types && pnpm generate:importmap\n" +
    "  pnpm dev        # site at " +
    siteUrl +
    ", CMS at /admin\n" +
    "\nEdit site.config.ts + theme.config.ts to finish rebranding, then `pnpm rebrand`.\n",
);
rl.close();
